import { Card, MathCategory } from './types.ts';

export interface DomainMeta {
  id: MathCategory;
  name: string;
  nameVi: string;
  color: string;
  glow: string;
  icon: string;
  description: string;
}

export const MATH_DOMAINS: Record<MathCategory, DomainMeta> = {
  NGUYEN_TO: {
    id: 'NGUYEN_TO',
    name: 'Prime Core',
    nameVi: 'Nguyên Tố',
    color: '#ef4444', // Red / Crimson
    glow: 'rgba(239, 68, 68, 0.5)',
    icon: 'Flame',
    description: 'Bản nguyên của toán học: Chỉ chia hết cho 1 và chính nó.',
  },
  CHINH_PHUONG: {
    id: 'CHINH_PHUONG',
    name: 'Perfect Square',
    nameVi: 'Chính Phương',
    color: '#f97316', // Orange
    glow: 'rgba(249, 115, 22, 0.5)',
    icon: 'Box',
    description: 'Sự cân bằng hình học: Bình phương của một số tự nhiên.',
  },
  DAI_SO: {
    id: 'DAI_SO',
    name: 'Algebra Rune',
    nameVi: 'Đại Số',
    color: '#eab308', // Gold
    glow: 'rgba(234, 179, 8, 0.5)',
    icon: 'Compass',
    description: 'Giải mã ẩn số x: Cân bằng hai vế phương trình.',
  },
  KHAI_CAN: {
    id: 'KHAI_CAN',
    name: 'Radical Root',
    nameVi: 'Khai Căn',
    color: '#84cc16', // Lime
    glow: 'rgba(132, 204, 22, 0.5)',
    icon: 'SquareDot',
    description: 'Nguồn cội tiềm ẩn: Tìm căn bậc hai và căn số học.',
  },
  LUY_THUA: {
    id: 'LUY_THUA',
    name: 'Exponent Bolt',
    nameVi: 'Lũy Thừa',
    color: '#10b981', // Emerald
    glow: 'rgba(16, 185, 129, 0.5)',
    icon: 'Zap',
    description: 'Năng lượng bùng nổ: Tăng trưởng cấp số nhân theo bậc mũ.',
  },
  AM_SO: {
    id: 'AM_SO',
    name: 'Negative Void',
    nameVi: 'Âm Số',
    color: '#06b6d4', // Cyan
    glow: 'rgba(6, 182, 212, 0.5)',
    icon: 'MinusCircle',
    description: 'Hư vô đối cực: Số âm và phép nhân đổi dấu huyền bí.',
  },
  CHIA_HET: {
    id: 'CHIA_HET',
    name: 'Divisibility Ray',
    nameVi: 'Chia Hết',
    color: '#3b82f6', // Blue
    glow: 'rgba(59, 130, 246, 0.5)',
    icon: 'Divide',
    description: 'Dấu hiệu phân tách: Kiểm tra chia hết cho 2, 3, 5, 9.',
  },
  PHAN_SO: {
    id: 'PHAN_SO',
    name: 'Fraction Shard',
    nameVi: 'Phân Số',
    color: '#8b5cf6', // Purple
    glow: 'rgba(139, 92, 246, 0.5)',
    icon: 'Layers',
    description: 'Mảnh ghép tỷ lệ: Tử số trên mẫu số bất biến.',
  },
  TUYET_DOI: {
    id: 'TUYET_DOI',
    name: 'Absolute Shield',
    nameVi: 'Tuyệt Đối',
    color: '#d946ef', // Fuchsia
    glow: 'rgba(217, 70, 239, 0.5)',
    icon: 'Shield',
    description: 'Khoảng cách thuần khiết: Biến mọi giá trị âm thành dương.',
  },
  UOC_BOI: {
    id: 'UOC_BOI',
    name: 'Factor & Multi',
    nameVi: 'Ước & Bội',
    color: '#ec4899', // Pink
    glow: 'rgba(236, 72, 153, 0.5)',
    icon: 'GitFork',
    description: 'Giao điểm liên kết: Ước chung lớn nhất và bội chung nhỏ nhất.',
  },
  // Advanced categories
  DAO_HAM: {
    id: 'DAO_HAM',
    name: 'Derivative Flow',
    nameVi: 'Đạo Hàm',
    color: '#14b8a6',
    glow: 'rgba(20, 184, 166, 0.5)',
    icon: 'TrendingUp',
    description: 'Tốc độ biến thiên tức thời.',
  },
  TICH_PHAN: {
    id: 'TICH_PHAN',
    name: 'Integral Area',
    nameVi: 'Tích Phân',
    color: '#6366f1',
    glow: 'rgba(99, 102, 241, 0.5)',
    icon: 'Activity',
    description: 'Tổng diện tích vô hạn bé.',
  },
  LOGARIT: {
    id: 'LOGARIT',
    name: 'Logarithm Key',
    nameVi: 'Logarit',
    color: '#f59e0b',
    glow: 'rgba(245, 158, 11, 0.5)',
    icon: 'Key',
    description: 'Nghịch đảo của lũy thừa.',
  },
  LUONG_GIAC: {
    id: 'LUONG_GIAC',
    name: 'Trig Orbit',
    nameVi: 'Lượng Giác',
    color: '#a855f7',
    glow: 'rgba(168, 85, 247, 0.5)',
    icon: 'CircleDot',
    description: 'Hàm sóng Sin, Cos trên đường tròn lượng giác.',
  },
  SO_PHUC: {
    id: 'SO_PHUC',
    name: 'Complex Void',
    nameVi: 'Số Phức',
    color: '#0ea5e9',
    glow: 'rgba(14, 165, 233, 0.5)',
    icon: 'Binary',
    description: 'Mặt phẳng phẳng ảo: Đơn vị ảo i² = -1.',
  },
  XAC_SUAT: {
    id: 'XAC_SUAT',
    name: 'Probability Matrix',
    nameVi: 'Xác Suất',
    color: '#10b981',
    glow: 'rgba(16, 185, 129, 0.5)',
    icon: 'Dice6',
    description: 'Dự báo không gian mẫu và tổ hợp.',
  },
};

// Generate 60 Cards: 10 Domains x 6 Cards
export const DECK_60_CARDS: Card[] = [
  // 1. NGUYEN_TO (6 cards)
  {
    id: 'card_nt_1',
    domainId: 'NGUYEN_TO',
    domainName: 'Prime Spark',
    domainNameVi: 'Tia Lửa Nguyên Tố',
    pointValue: 6,
    rarity: 'Common',
    skillName: 'Khởi Điểm',
    skillDesc: 'Nhận 6 điểm khi giải đúng câu hỏi số nguyên tố.',
    elementColor: MATH_DOMAINS.NGUYEN_TO.color,
    accentGlow: MATH_DOMAINS.NGUYEN_TO.glow,
    iconName: 'Flame',
  },
  {
    id: 'card_nt_2',
    domainId: 'NGUYEN_TO',
    domainName: 'Prime Core',
    domainNameVi: 'Lõi Nguyên Tố',
    pointValue: 10,
    rarity: 'Common',
    skillName: 'Thấu Kính',
    skillDesc: 'Cho thêm +3 giây suy nghĩ cho câu hỏi kế tiếp.',
    elementColor: MATH_DOMAINS.NGUYEN_TO.color,
    accentGlow: MATH_DOMAINS.NGUYEN_TO.glow,
    iconName: 'Flame',
  },
  {
    id: 'card_nt_3',
    domainId: 'NGUYEN_TO',
    domainName: 'Prime Blaze',
    domainNameVi: 'Hỏa Nguyên Tố',
    pointValue: 14,
    rarity: 'Rare',
    skillName: 'Tiên Đoán',
    skillDesc: 'Xem trước hệ bài của lá trên đỉnh bộ bài.',
    elementColor: MATH_DOMAINS.NGUYEN_TO.color,
    accentGlow: MATH_DOMAINS.NGUYEN_TO.glow,
    iconName: 'Flame',
  },
  {
    id: 'card_nt_4',
    domainId: 'NGUYEN_TO',
    domainName: 'Prime Sentinel',
    domainNameVi: 'Hộ Thần Nguyên Tố',
    pointValue: 18,
    rarity: 'Rare',
    skillName: 'Bảo Vệ Lượt',
    skillDesc: 'Cộng +2 điểm thưởng cho mỗi lá bài khác trên bàn.',
    elementColor: MATH_DOMAINS.NGUYEN_TO.color,
    accentGlow: MATH_DOMAINS.NGUYEN_TO.glow,
    iconName: 'Flame',
  },
  {
    id: 'card_nt_5',
    domainId: 'NGUYEN_TO',
    domainName: 'Prime Zenith',
    domainNameVi: 'Đỉnh Quang Nguyên Tố',
    pointValue: 24,
    rarity: 'Epic',
    skillName: 'Sàng Eratosthenes',
    skillDesc: 'Nếu giải đúng trong 5 giây đầu, nhận gấp rưỡi (+50%) điểm.',
    elementColor: MATH_DOMAINS.NGUYEN_TO.color,
    accentGlow: MATH_DOMAINS.NGUYEN_TO.glow,
    iconName: 'Flame',
  },
  {
    id: 'card_nt_6',
    domainId: 'NGUYEN_TO',
    domainName: 'God of Primes',
    domainNameVi: 'Thần Tích Nguyên Tố',
    pointValue: 30,
    rarity: 'Legendary',
    skillName: 'Bản Nguyên Vô Hạn',
    skillDesc: 'Cộng 30 điểm và lá này tự động khóa an toàn không bị mất nếu Bust.',
    elementColor: MATH_DOMAINS.NGUYEN_TO.color,
    accentGlow: MATH_DOMAINS.NGUYEN_TO.glow,
    iconName: 'Flame',
  },

  // 2. CHINH_PHUONG (6 cards)
  {
    id: 'card_cp_1',
    domainId: 'CHINH_PHUONG',
    domainName: 'Square Shard',
    domainNameVi: 'Mảnh Chính Phương',
    pointValue: 6,
    rarity: 'Common',
    skillName: 'Vuông Vắn',
    skillDesc: 'Tích lũy 6 điểm cơ bản.',
    elementColor: MATH_DOMAINS.CHINH_PHUONG.color,
    accentGlow: MATH_DOMAINS.CHINH_PHUONG.glow,
    iconName: 'Box',
  },
  {
    id: 'card_cp_2',
    domainId: 'CHINH_PHUONG',
    domainName: 'Square Block',
    domainNameVi: 'Khối Chính Phương',
    pointValue: 10,
    rarity: 'Common',
    skillName: 'Bình Phương',
    skillDesc: 'Nếu giải đúng chuỗi combo >= 2, cộng thêm 4 điểm.',
    elementColor: MATH_DOMAINS.CHINH_PHUONG.color,
    accentGlow: MATH_DOMAINS.CHINH_PHUONG.glow,
    iconName: 'Box',
  },
  {
    id: 'card_cp_3',
    domainId: 'CHINH_PHUONG',
    domainName: 'Square Prism',
    domainNameVi: 'Lăng Kính Chính Phương',
    pointValue: 15,
    rarity: 'Rare',
    skillName: 'Cân Đối',
    skillDesc: 'Giúp chuyển 5 điểm hiện tại vào kho an toàn ngay lập tức.',
    elementColor: MATH_DOMAINS.CHINH_PHUONG.color,
    accentGlow: MATH_DOMAINS.CHINH_PHUONG.glow,
    iconName: 'Box',
  },
  {
    id: 'card_cp_4',
    domainId: 'CHINH_PHUONG',
    domainName: 'Square Matrix',
    domainNameVi: 'Ma Trận Chính Phương',
    pointValue: 20,
    rarity: 'Rare',
    skillName: 'Tích Lũy Bội Phần',
    skillDesc: 'Cộng thêm +5 điểm nếu tổng số lá trên bàn là số chẵn.',
    elementColor: MATH_DOMAINS.CHINH_PHUONG.color,
    accentGlow: MATH_DOMAINS.CHINH_PHUONG.glow,
    iconName: 'Box',
  },
  {
    id: 'card_cp_5',
    domainId: 'CHINH_PHUONG',
    domainName: 'Square Colossus',
    domainNameVi: 'Cự Thạch Chính Phương',
    pointValue: 25,
    rarity: 'Epic',
    skillName: 'Cộng Hưởng Bình Phương',
    skillDesc: 'Tăng x1.5 điểm cho toàn bộ lá hệ Chính Phương khác trên bàn.',
    elementColor: MATH_DOMAINS.CHINH_PHUONG.color,
    accentGlow: MATH_DOMAINS.CHINH_PHUONG.glow,
    iconName: 'Box',
  },
  {
    id: 'card_cp_6',
    domainId: 'CHINH_PHUONG',
    domainName: 'Infinite Tessellation',
    domainNameVi: 'Bảo Đồ Chính Phương',
    pointValue: 32,
    rarity: 'Legendary',
    skillName: 'Hoàn Hảo Tuyệt Đối',
    skillDesc: 'Nhận 32 điểm và giảm 50% nguy cơ Bust lá kế tiếp.',
    elementColor: MATH_DOMAINS.CHINH_PHUONG.color,
    accentGlow: MATH_DOMAINS.CHINH_PHUONG.glow,
    iconName: 'Box',
  },

  // 3. DAI_SO (6 cards)
  {
    id: 'card_ds_1',
    domainId: 'DAI_SO',
    domainName: 'Linear Line',
    domainNameVi: 'Đường Tuyến Tính',
    pointValue: 7,
    rarity: 'Common',
    skillName: 'Tìm Ẩn Số',
    skillDesc: 'Tích 7 điểm khi giải đúng phương trình bậc nhất.',
    elementColor: MATH_DOMAINS.DAI_SO.color,
    accentGlow: MATH_DOMAINS.DAI_SO.glow,
    iconName: 'Compass',
  },
  {
    id: 'card_ds_2',
    domainId: 'DAI_SO',
    domainName: 'Algebra Rune',
    domainNameVi: 'Ấn Đại Số',
    pointValue: 12,
    rarity: 'Common',
    skillName: 'Chuyển Vế',
    skillDesc: 'Đổi dấu khó khăn: Thêm 4 giây suy nghĩ cho câu hỏi.',
    elementColor: MATH_DOMAINS.DAI_SO.color,
    accentGlow: MATH_DOMAINS.DAI_SO.glow,
    iconName: 'Compass',
  },
  {
    id: 'card_ds_3',
    domainId: 'DAI_SO',
    domainName: 'Equation Weaver',
    domainNameVi: 'Thợ Dệt Phương Trình',
    pointValue: 16,
    rarity: 'Rare',
    skillName: 'Khử Ẩn Số',
    skillDesc: 'Làm chậm tốc độ trả lời của đối thủ lượt sau 3 giây.',
    elementColor: MATH_DOMAINS.DAI_SO.color,
    accentGlow: MATH_DOMAINS.DAI_SO.glow,
    iconName: 'Compass',
  },
  {
    id: 'card_ds_4',
    domainId: 'DAI_SO',
    domainName: 'Algebraic Nexus',
    domainNameVi: 'Cội Nguồn Đại Số',
    pointValue: 20,
    rarity: 'Rare',
    skillName: 'Đẳng Thức Vàng',
    skillDesc: 'Cộng thêm +6 điểm nếu giải đúng mà không dùng Rune.',
    elementColor: MATH_DOMAINS.DAI_SO.color,
    accentGlow: MATH_DOMAINS.DAI_SO.glow,
    iconName: 'Compass',
  },
  {
    id: 'card_ds_5',
    domainId: 'DAI_SO',
    domainName: 'Master Equation',
    domainNameVi: 'Đại Trọng Phương Trình',
    pointValue: 26,
    rarity: 'Epic',
    skillName: 'Nghiệm Duy Nhất',
    skillDesc: 'Nhận 26 điểm và cho phép đổi 1 câu hỏi nếu không biết làm.',
    elementColor: MATH_DOMAINS.DAI_SO.color,
    accentGlow: MATH_DOMAINS.DAI_SO.glow,
    iconName: 'Compass',
  },
  {
    id: 'card_ds_6',
    domainId: 'DAI_SO',
    domainName: 'Omni Equation',
    domainNameVi: 'Chân Lý Đại Số',
    pointValue: 32,
    rarity: 'Legendary',
    skillName: 'Vạn Vật Quy Hồi',
    skillDesc: '32 điểm và nhân đôi điểm cho lá bài kế tiếp nếu rút tiếp.',
    elementColor: MATH_DOMAINS.DAI_SO.color,
    accentGlow: MATH_DOMAINS.DAI_SO.glow,
    iconName: 'Compass',
  },

  // 4. KHAI_CAN (6 cards)
  {
    id: 'card_kc_1',
    domainId: 'KHAI_CAN',
    domainName: 'Root Sprout',
    domainNameVi: 'Mầm Khai Căn',
    pointValue: 6,
    rarity: 'Common',
    skillName: 'Gốc Rễ',
    skillDesc: 'Tích 6 điểm căn số học.',
    elementColor: MATH_DOMAINS.KHAI_CAN.color,
    accentGlow: MATH_DOMAINS.KHAI_CAN.glow,
    iconName: 'SquareDot',
  },
  {
    id: 'card_kc_2',
    domainId: 'KHAI_CAN',
    domainName: 'Radical Branch',
    domainNameVi: 'Nhánh Căn Số',
    pointValue: 11,
    rarity: 'Common',
    skillName: 'Khai Triển',
    skillDesc: 'Tăng 3 điểm cho mỗi lá bài trên bàn có giá trị < 10.',
    elementColor: MATH_DOMAINS.KHAI_CAN.color,
    accentGlow: MATH_DOMAINS.KHAI_CAN.glow,
    iconName: 'SquareDot',
  },
  {
    id: 'card_kc_3',
    domainId: 'KHAI_CAN',
    domainName: 'Ancient Root',
    domainNameVi: 'Cổ Thụ Khai Căn',
    pointValue: 15,
    rarity: 'Rare',
    skillName: 'Độ Cứng Gốc Cây',
    skillDesc: 'Giảm 10 điểm phạt nếu bị Bust ở lượt này.',
    elementColor: MATH_DOMAINS.KHAI_CAN.color,
    accentGlow: MATH_DOMAINS.KHAI_CAN.glow,
    iconName: 'SquareDot',
  },
  {
    id: 'card_kc_4',
    domainId: 'KHAI_CAN',
    domainName: 'Radical Crystal',
    domainNameVi: 'Tinh Thể Khai Căn',
    pointValue: 19,
    rarity: 'Rare',
    skillName: 'Căn Thức Đồng Nhất',
    skillDesc: 'Cho phép rút lại câu hỏi nếu độ khó là 4 sao.',
    elementColor: MATH_DOMAINS.KHAI_CAN.color,
    accentGlow: MATH_DOMAINS.KHAI_CAN.glow,
    iconName: 'SquareDot',
  },
  {
    id: 'card_kc_5',
    domainId: 'KHAI_CAN',
    domainName: 'World Tree Root',
    domainNameVi: 'Địa Mạch Khai Căn',
    pointValue: 25,
    rarity: 'Epic',
    skillName: 'Ăn Sâu Lòng Đất',
    skillDesc: 'Khi Bank, nhận thêm 8 điểm thưởng an toàn.',
    elementColor: MATH_DOMAINS.KHAI_CAN.color,
    accentGlow: MATH_DOMAINS.KHAI_CAN.glow,
    iconName: 'SquareDot',
  },
  {
    id: 'card_kc_6',
    domainId: 'KHAI_CAN',
    domainName: 'Yggdrasil Core',
    domainNameVi: 'Thần Mộc Khai Căn',
    pointValue: 30,
    rarity: 'Legendary',
    skillName: 'Nguồn Cội Sự Sống',
    skillDesc: '30 điểm và hồi phục 15 HP cho người chơi.',
    elementColor: MATH_DOMAINS.KHAI_CAN.color,
    accentGlow: MATH_DOMAINS.KHAI_CAN.glow,
    iconName: 'SquareDot',
  },

  // 5. LUY_THUA (6 cards)
  {
    id: 'card_lt_1',
    domainId: 'LUY_THUA',
    domainName: 'Power Spark',
    domainNameVi: 'Tia Lũy Thừa',
    pointValue: 7,
    rarity: 'Common',
    skillName: 'Số Mũ Nhỏ',
    skillDesc: 'Tích 7 điểm lũy thừa cơ bản.',
    elementColor: MATH_DOMAINS.LUY_THUA.color,
    accentGlow: MATH_DOMAINS.LUY_THUA.glow,
    iconName: 'Zap',
  },
  {
    id: 'card_lt_2',
    domainId: 'LUY_THUA',
    domainName: 'Exponent Surge',
    domainNameVi: 'Sóng Lũy Thừa',
    pointValue: 12,
    rarity: 'Common',
    skillName: 'Cơ Số Nhân Đôi',
    skillDesc: 'Tăng thêm 5 điểm nếu bạn có trên 3 lá trên bàn.',
    elementColor: MATH_DOMAINS.LUY_THUA.color,
    accentGlow: MATH_DOMAINS.LUY_THUA.glow,
    iconName: 'Zap',
  },
  {
    id: 'card_lt_3',
    domainId: 'LUY_THUA',
    domainName: 'Storm Exponent',
    domainNameVi: 'Bão Lũy Thừa',
    pointValue: 16,
    rarity: 'Rare',
    skillName: 'Tia Sét Số Mũ',
    skillDesc: 'Tăng x1.25 tổng điểm của cả lượt hiện tại.',
    elementColor: MATH_DOMAINS.LUY_THUA.color,
    accentGlow: MATH_DOMAINS.LUY_THUA.glow,
    iconName: 'Zap',
  },
  {
    id: 'card_lt_4',
    domainId: 'LUY_THUA',
    domainName: 'Supernova Exponent',
    domainNameVi: 'Siêu Tân Tinh Lũy Thừa',
    pointValue: 22,
    rarity: 'Rare',
    skillName: 'Bùng Nổ Bậc Cao',
    skillDesc: 'Cộng thêm +8 điểm nếu đối thủ đang dẫn điểm trước.',
    elementColor: MATH_DOMAINS.LUY_THUA.color,
    accentGlow: MATH_DOMAINS.LUY_THUA.glow,
    iconName: 'Zap',
  },
  {
    id: 'card_lt_5',
    domainId: 'LUY_THUA',
    domainName: 'Overcharge Exponent',
    domainNameVi: 'Cường Hóa Lũy Thừa',
    pointValue: 28,
    rarity: 'Epic',
    skillName: 'Chuỗi Phản Ứng',
    skillDesc: 'Nếu tiếp tục Draw thành công, lá kế tiếp được x2 điểm.',
    elementColor: MATH_DOMAINS.LUY_THUA.color,
    accentGlow: MATH_DOMAINS.LUY_THUA.glow,
    iconName: 'Zap',
  },
  {
    id: 'card_lt_6',
    domainId: 'LUY_THUA',
    domainName: 'Titan of Exponents',
    domainNameVi: 'Thần Lôi Lũy Thừa',
    pointValue: 34,
    rarity: 'Legendary',
    skillName: 'Vô Cực Bùng Cháy',
    skillDesc: '34 điểm khổng lồ đưa bạn tiến gần đến chiến thắng.',
    elementColor: MATH_DOMAINS.LUY_THUA.color,
    accentGlow: MATH_DOMAINS.LUY_THUA.glow,
    iconName: 'Zap',
  },

  // 6. AM_SO (6 cards)
  {
    id: 'card_as_1',
    domainId: 'AM_SO',
    domainName: 'Negative Mote',
    domainNameVi: 'Bụi Âm Số',
    pointValue: 6,
    rarity: 'Common',
    skillName: 'Dấu Trừ Nhỏ',
    skillDesc: 'Tích 6 điểm quy ước âm.',
    elementColor: MATH_DOMAINS.AM_SO.color,
    accentGlow: MATH_DOMAINS.AM_SO.glow,
    iconName: 'MinusCircle',
  },
  {
    id: 'card_as_2',
    domainId: 'AM_SO',
    domainName: 'Negative Veil',
    domainNameVi: 'Màn Đêm Âm Số',
    pointValue: 11,
    rarity: 'Common',
    skillName: 'Đổi Dấu Nghịch Đảo',
    skillDesc: 'Cộng thêm +4 điểm khi giải đúng phép nhân 2 số âm.',
    elementColor: MATH_DOMAINS.AM_SO.color,
    accentGlow: MATH_DOMAINS.AM_SO.glow,
    iconName: 'MinusCircle',
  },
  {
    id: 'card_as_3',
    domainId: 'AM_SO',
    domainName: 'Frost Negative',
    domainNameVi: 'Băng Giá Âm Số',
    pointValue: 15,
    rarity: 'Rare',
    skillName: 'Độ Âm Tuyệt Đối',
    skillDesc: 'Đóng băng 1 lá trên bàn, bảo vệ khỏi nguy cơ bust.',
    elementColor: MATH_DOMAINS.AM_SO.color,
    accentGlow: MATH_DOMAINS.AM_SO.glow,
    iconName: 'MinusCircle',
  },
  {
    id: 'card_as_4',
    domainId: 'AM_SO',
    domainName: 'Shadow Negative',
    domainNameVi: 'Bóng Tối Âm Số',
    pointValue: 20,
    rarity: 'Rare',
    skillName: 'Phản Đòn Trục Số',
    skillDesc: 'Trừ 5 điểm an toàn của đối thủ và cộng vào lượt của bạn.',
    elementColor: MATH_DOMAINS.AM_SO.color,
    accentGlow: MATH_DOMAINS.AM_SO.glow,
    iconName: 'MinusCircle',
  },
  {
    id: 'card_as_5',
    domainId: 'AM_SO',
    domainName: 'Abyssal Negative',
    domainNameVi: 'Vực Thẳm Âm Số',
    pointValue: 26,
    rarity: 'Epic',
    skillName: 'Âm Nhân Âm Hóa Dương',
    skillDesc: 'Biến toàn bộ điểm trừ hoặc rủi ro thành điểm dương (+26).',
    elementColor: MATH_DOMAINS.AM_SO.color,
    accentGlow: MATH_DOMAINS.AM_SO.glow,
    iconName: 'MinusCircle',
  },
  {
    id: 'card_as_6',
    domainId: 'AM_SO',
    domainName: 'Lord of Negative',
    domainNameVi: 'Bá Chủ Âm Số',
    pointValue: 31,
    rarity: 'Legendary',
    skillName: 'Đảo Chiều Càn Khôn',
    skillDesc: '31 điểm và ép đối thủ phải chịu độ khó cao hơn lượt tới.',
    elementColor: MATH_DOMAINS.AM_SO.color,
    accentGlow: MATH_DOMAINS.AM_SO.glow,
    iconName: 'MinusCircle',
  },

  // 7. CHIA_HET (6 cards)
  {
    id: 'card_ch_1',
    domainId: 'CHIA_HET',
    domainName: 'Divisible Ray',
    domainNameVi: 'Tia Chia Hết',
    pointValue: 6,
    rarity: 'Common',
    skillName: 'Dấu Hiệu Cơ Bản',
    skillDesc: 'Tích 6 điểm quy tắc chia hết.',
    elementColor: MATH_DOMAINS.CHIA_HET.color,
    accentGlow: MATH_DOMAINS.CHIA_HET.glow,
    iconName: 'Divide',
  },
  {
    id: 'card_ch_2',
    domainId: 'CHIA_HET',
    domainName: 'Harmonic Divisor',
    domainNameVi: 'Gia Tốc Phép Chia',
    pointValue: 11,
    rarity: 'Common',
    skillName: 'Quy Tắc Số 3 & 9',
    skillDesc: 'Cộng thêm 4 điểm nếu tổng điểm các lá trên bàn chia hết cho 3.',
    elementColor: MATH_DOMAINS.CHIA_HET.color,
    accentGlow: MATH_DOMAINS.CHIA_HET.glow,
    iconName: 'Divide',
  },
  {
    id: 'card_ch_3',
    domainId: 'CHIA_HET',
    domainName: 'Prism Divisor',
    domainNameVi: 'Lăng Kính Chia Hết',
    pointValue: 15,
    rarity: 'Rare',
    skillName: 'Chia Đều Rủi Ro',
    skillDesc: 'Nếu Bust, giữ lại được 30% điểm lượt thay vì mất trắng.',
    elementColor: MATH_DOMAINS.CHIA_HET.color,
    accentGlow: MATH_DOMAINS.CHIA_HET.glow,
    iconName: 'Divide',
  },
  {
    id: 'card_ch_4',
    domainId: 'CHIA_HET',
    domainName: 'Crystal Divisor',
    domainNameVi: 'Bảo Thạch Chia Hết',
    pointValue: 21,
    rarity: 'Rare',
    skillName: 'Phần Dư Bằng Không',
    skillDesc: 'Tặng thêm 6 điểm thưởng khi giải đúng trong 7 giây.',
    elementColor: MATH_DOMAINS.CHIA_HET.color,
    accentGlow: MATH_DOMAINS.CHIA_HET.glow,
    iconName: 'Divide',
  },
  {
    id: 'card_ch_5',
    domainId: 'CHIA_HET',
    domainName: 'Grand Divisor',
    domainNameVi: 'Đại Trí Phép Chia',
    pointValue: 27,
    rarity: 'Epic',
    skillName: 'Hoàn Hảo Chia Cắt',
    skillDesc: 'Cho phép rút thêm 1 lá mà được xem trước cả 2 lá kế tiếp.',
    elementColor: MATH_DOMAINS.CHIA_HET.color,
    accentGlow: MATH_DOMAINS.CHIA_HET.glow,
    iconName: 'Divide',
  },
  {
    id: 'card_ch_6',
    domainId: 'CHIA_HET',
    domainName: 'Sovereign of Divisors',
    domainNameVi: 'Thần Minh Chia Hết',
    pointValue: 33,
    rarity: 'Legendary',
    skillName: 'Chân Thức Phân Định',
    skillDesc: 'Nhận 33 điểm và cộng 10 điểm an toàn cho mỗi 3 lá trên bàn.',
    elementColor: MATH_DOMAINS.CHIA_HET.color,
    accentGlow: MATH_DOMAINS.CHIA_HET.glow,
    iconName: 'Divide',
  },

  // 8. PHAN_SO (6 cards)
  {
    id: 'card_ps_1',
    domainId: 'PHAN_SO',
    domainName: 'Fraction Pebble',
    domainNameVi: 'Mảnh Phân Số',
    pointValue: 7,
    rarity: 'Common',
    skillName: 'Tử & Mẫu',
    skillDesc: 'Tích 7 điểm phân số cơ bản.',
    elementColor: MATH_DOMAINS.PHAN_SO.color,
    accentGlow: MATH_DOMAINS.PHAN_SO.glow,
    iconName: 'Layers',
  },
  {
    id: 'card_ps_2',
    domainId: 'PHAN_SO',
    domainName: 'Fraction Ratio',
    domainNameVi: 'Tỉ Lệ Phân Số',
    pointValue: 12,
    rarity: 'Common',
    skillName: 'Rút Gọn Tối Giản',
    skillDesc: 'Tối ưu hóa điểm: Cộng thêm 5 điểm thưởng.',
    elementColor: MATH_DOMAINS.PHAN_SO.color,
    accentGlow: MATH_DOMAINS.PHAN_SO.glow,
    iconName: 'Layers',
  },
  {
    id: 'card_ps_3',
    domainId: 'PHAN_SO',
    domainName: 'Harmonic Fraction',
    domainNameVi: 'Điều Hòa Phân Số',
    pointValue: 16,
    rarity: 'Rare',
    skillName: 'Quy Đồng Mẫu Số',
    skillDesc: 'Đồng bộ điểm: Chuyển 8 điểm vào kho an toàn ngay lập tức.',
    elementColor: MATH_DOMAINS.PHAN_SO.color,
    accentGlow: MATH_DOMAINS.PHAN_SO.glow,
    iconName: 'Layers',
  },
  {
    id: 'card_ps_4',
    domainId: 'PHAN_SO',
    domainName: 'Golden Ratio',
    domainNameVi: 'Tỉ Lệ Vàng Phân Số',
    pointValue: 22,
    rarity: 'Rare',
    skillName: 'Tỷ Lệ Hoàn Mỹ',
    skillDesc: 'Tăng 25% điểm cho toàn bộ lượt nếu giải đúng câu phân số.',
    elementColor: MATH_DOMAINS.PHAN_SO.color,
    accentGlow: MATH_DOMAINS.PHAN_SO.glow,
    iconName: 'Layers',
  },
  {
    id: 'card_ps_5',
    domainId: 'PHAN_SO',
    domainName: 'Fractional Aegis',
    domainNameVi: 'Khiên Phân Số',
    pointValue: 27,
    rarity: 'Epic',
    skillName: 'Bức Tường Phân Thân',
    skillDesc: 'Lá này tạo 1 khiên chặn Bust cho lần rút tiếp theo.',
    elementColor: MATH_DOMAINS.PHAN_SO.color,
    accentGlow: MATH_DOMAINS.PHAN_SO.glow,
    iconName: 'Layers',
  },
  {
    id: 'card_ps_6',
    domainId: 'PHAN_SO',
    domainName: 'Archmage of Fractions',
    domainNameVi: 'Pháp Hoàng Phân Số',
    pointValue: 33,
    rarity: 'Legendary',
    skillName: 'Vô Hạn Phân Tách',
    skillDesc: '33 điểm và hồi sinh 10 HP cho bạn.',
    elementColor: MATH_DOMAINS.PHAN_SO.color,
    accentGlow: MATH_DOMAINS.PHAN_SO.glow,
    iconName: 'Layers',
  },

  // 9. TUYET_DOI (6 cards)
  {
    id: 'card_td_1',
    domainId: 'TUYET_DOI',
    domainName: 'Absolute Spark',
    domainNameVi: 'Tia Trị Tuyệt Đối',
    pointValue: 6,
    rarity: 'Common',
    skillName: 'Khoảng Cách',
    skillDesc: 'Tích 6 điểm khoảng cách thuần túy.',
    elementColor: MATH_DOMAINS.TUYET_DOI.color,
    accentGlow: MATH_DOMAINS.TUYET_DOI.glow,
    iconName: 'Shield',
  },
  {
    id: 'card_td_2',
    domainId: 'TUYET_DOI',
    domainName: 'Absolute Barrier',
    domainNameVi: 'Hào Quang Tuyệt Đối',
    pointValue: 11,
    rarity: 'Common',
    skillName: 'Luôn Dương',
    skillDesc: 'Mọi điểm số trong lượt này được đảm bảo không thể âm.',
    elementColor: MATH_DOMAINS.TUYET_DOI.color,
    accentGlow: MATH_DOMAINS.TUYET_DOI.glow,
    iconName: 'Shield',
  },
  {
    id: 'card_td_3',
    domainId: 'TUYET_DOI',
    domainName: 'Absolute Ward',
    domainNameVi: 'Hộ Giới Tuyệt Đối',
    pointValue: 16,
    rarity: 'Rare',
    skillName: 'Bất Biến',
    skillDesc: 'Không bị ảnh hưởng bởi kỹ năng giảm thời gian từ đối thủ.',
    elementColor: MATH_DOMAINS.TUYET_DOI.color,
    accentGlow: MATH_DOMAINS.TUYET_DOI.glow,
    iconName: 'Shield',
  },
  {
    id: 'card_td_4',
    domainId: 'TUYET_DOI',
    domainName: 'Absolute Mirror',
    domainNameVi: 'Gương Phản Tuyệt Đối',
    pointValue: 21,
    rarity: 'Rare',
    skillName: 'Phản Chiếu Khoảng Cách',
    skillDesc: 'Nhận 21 điểm và sao chép 5 điểm từ kho đối thủ.',
    elementColor: MATH_DOMAINS.TUYET_DOI.color,
    accentGlow: MATH_DOMAINS.TUYET_DOI.glow,
    iconName: 'Shield',
  },
  {
    id: 'card_td_5',
    domainId: 'TUYET_DOI',
    domainName: 'Absolute Bastion',
    domainNameVi: 'Pháo Đài Tuyệt Đối',
    pointValue: 27,
    rarity: 'Epic',
    skillName: 'Khiên Bất Hoại',
    skillDesc: 'Nếu bị Bust, lập tức giữ lại 50% điểm thay vì 0.',
    elementColor: MATH_DOMAINS.TUYET_DOI.color,
    accentGlow: MATH_DOMAINS.TUYET_DOI.glow,
    iconName: 'Shield',
  },
  {
    id: 'card_td_6',
    domainId: 'TUYET_DOI',
    domainName: 'Avatar of Absoluteness',
    domainNameVi: 'Thần Tượng Tuyệt Đối',
    pointValue: 32,
    rarity: 'Legendary',
    skillName: 'Chân Không Tuyệt Đối',
    skillDesc: '32 điểm và bảo đảm 100% lá tiếp theo không Bust.',
    elementColor: MATH_DOMAINS.TUYET_DOI.color,
    accentGlow: MATH_DOMAINS.TUYET_DOI.glow,
    iconName: 'Shield',
  },

  // 10. UOC_BOI (6 cards)
  {
    id: 'card_ub_1',
    domainId: 'UOC_BOI',
    domainName: 'Factor Seed',
    domainNameVi: 'Mầm Ước Bội',
    pointValue: 7,
    rarity: 'Common',
    skillName: 'Ước Số',
    skillDesc: 'Tích 7 điểm ước chung.',
    elementColor: MATH_DOMAINS.UOC_BOI.color,
    accentGlow: MATH_DOMAINS.UOC_BOI.glow,
    iconName: 'GitFork',
  },
  {
    id: 'card_ub_2',
    domainId: 'UOC_BOI',
    domainName: 'Common Multiplier',
    domainNameVi: 'Bội Chung Liên Kết',
    pointValue: 12,
    rarity: 'Common',
    skillName: 'BCNN',
    skillDesc: 'Cộng thêm +4 điểm cho mỗi lá khác hệ đang có trên bàn.',
    elementColor: MATH_DOMAINS.UOC_BOI.color,
    accentGlow: MATH_DOMAINS.UOC_BOI.glow,
    iconName: 'GitFork',
  },
  {
    id: 'card_ub_3',
    domainId: 'UOC_BOI',
    domainName: 'Greatest Factor',
    domainNameVi: 'Ước Chung Lớn Nhất',
    pointValue: 17,
    rarity: 'Rare',
    skillName: 'UCLN Tối Đa',
    skillDesc: 'Cho thêm +5 giây suy nghĩ và rút gọn độ khó câu hỏi.',
    elementColor: MATH_DOMAINS.UOC_BOI.color,
    accentGlow: MATH_DOMAINS.UOC_BOI.glow,
    iconName: 'GitFork',
  },
  {
    id: 'card_ub_4',
    domainId: 'UOC_BOI',
    domainName: 'Multiplicity Core',
    domainNameVi: 'Lõi Bội Số',
    pointValue: 22,
    rarity: 'Rare',
    skillName: 'Cộng Hưởng Bội Số',
    skillDesc: 'Tăng thêm 8 điểm nếu trên bàn có từ 3 lá trở lên.',
    elementColor: MATH_DOMAINS.UOC_BOI.color,
    accentGlow: MATH_DOMAINS.UOC_BOI.glow,
    iconName: 'GitFork',
  },
  {
    id: 'card_ub_5',
    domainId: 'UOC_BOI',
    domainName: 'Tide of Factors',
    domainNameVi: 'Triều Dâng Ước Bội',
    pointValue: 28,
    rarity: 'Epic',
    skillName: 'Liên Kết Vô Tận',
    skillDesc: 'Tự động Bank điểm an toàn nếu tổng điểm lượt vượt qua 40.',
    elementColor: MATH_DOMAINS.UOC_BOI.color,
    accentGlow: MATH_DOMAINS.UOC_BOI.glow,
    iconName: 'GitFork',
  },
  {
    id: 'card_ub_6',
    domainId: 'UOC_BOI',
    domainName: 'Ancient Harmonizer',
    domainNameVi: 'Hòa Hợp Giới Ước Bội',
    pointValue: 34,
    rarity: 'Legendary',
    skillName: 'Giao Thoa Thần Giới',
    skillDesc: '34 điểm thần thoại và tăng thêm 1 lần dùng cho 1 Rune đã chọn.',
    elementColor: MATH_DOMAINS.UOC_BOI.color,
    accentGlow: MATH_DOMAINS.UOC_BOI.glow,
    iconName: 'GitFork',
  },
];
