import { RuneDef } from './types.ts';

export const ALL_RUNES: RuneDef[] = [
  // 🔴 NHÓM PHÒNG THỦ (DEFENSE)
  {
    id: 'rune_revive',
    name: 'Rune Hồi Sinh',
    category: 'DEFENSE',
    categoryNameVi: 'Phòng Thủ',
    icon: 'ShieldAlert',
    color: '#ef4444',
    description: 'Cứu 50% điểm an toàn khi bị BUST (Duy nhất 1 lần/trận).',
    persistentEffectDesc: 'HỒI SINH BẢO MỆNH (DUY NHẤT 1 LẦN/TRẬN): Khi gặp rủi ro BUST nổ lượt, tự động cứu lại 50% điểm số lượt đó vào kho an toàn. Chỉ kích hoạt ĐÚNG 1 LẦN trong cả trận đấu!',
    limitType: 'once_per_match',
    maxUses: 1,
    unlockedLevel: 1,
  },
  {
    id: 'rune_shield',
    name: 'Rune Khiên Chắn',
    category: 'DEFENSE',
    categoryNameVi: 'Phòng Thủ',
    icon: 'Shield',
    color: '#f87171',
    description: 'Chặn rủi ro BUST trùng hệ (1 lần/lượt).',
    persistentEffectDesc: 'KHIÊN HỘ MỆNH (1 LẦN/LƯỢT): Tự động chặn đứng 1 lần BUST trùng hệ đầu tiên trong mỗi lượt thi đấu!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },
  {
    id: 'rune_insurance',
    name: 'Rune Bảo Hiểm',
    category: 'DEFENSE',
    categoryNameVi: 'Phòng Thủ',
    icon: 'Lock',
    color: '#fb923c',
    description: 'Khóa điểm bài trên bàn vào kho (1 lần/lượt).',
    persistentEffectDesc: 'BẢO HIỂM KHO (1 LẦN/LƯỢT): Khi tích được từ 2 lá bài trở lên trên bàn, lá bài điểm cao nhất tự động được khóa vào kho an toàn (tối đa 1 lần/lượt)!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },
  {
    id: 'rune_retry',
    name: 'Rune Sửa Sai',
    category: 'DEFENSE',
    categoryNameVi: 'Phòng Thủ',
    icon: 'RotateCcw',
    color: '#f43f5e',
    description: 'Cho phép làm lại câu hỏi Toán (1 lần/lượt).',
    persistentEffectDesc: 'SỬA SAI (1 LẦN/LƯỢT): Nếu trả lời chưa đúng, được làm lại ngay một lần với thêm 15 giây hồi phục (tối đa 1 lần/lượt)!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },

  // 🔵 NHÓM THỜI GIAN (TIME)
  {
    id: 'rune_freeze',
    name: 'Rune Đóng Băng',
    category: 'TIME',
    categoryNameVi: 'Thời Gian',
    icon: 'Snowflake',
    color: '#38bdf8',
    description: 'Gia hạn thời gian tính toán.',
    persistentEffectDesc: 'THỜI KHÔNG: Mọi câu hỏi Toán trong suốt trận đấu của bạn đều được tự động cộng thêm +20 giây suy nghĩ!',
    limitType: 'continuous',
    maxUses: 999,
    unlockedLevel: 1,
  },
  {
    id: 'rune_haste',
    name: 'Rune Tăng Tốc',
    category: 'TIME',
    categoryNameVi: 'Thời Gian',
    icon: 'Zap',
    color: '#60a5fa',
    description: 'Gây áp lực tốc độ lên đối thủ.',
    persistentEffectDesc: 'ÁP CHẾ: Đối thủ của bạn bị trừ 8 giây thời gian suy nghĩ trong mọi lượt thi đấu của họ suốt cả trận!',
    limitType: 'continuous',
    maxUses: 999,
    unlockedLevel: 1,
  },
  {
    id: 'rune_time_plus',
    name: 'Rune Thời Gian',
    category: 'TIME',
    categoryNameVi: 'Thời Gian',
    icon: 'Clock',
    color: '#0ea5e9',
    description: 'Thời gian tư duy dồi dào và thưởng tốc độ.',
    persistentEffectDesc: 'VĨNH HẰNG: Luôn được hưởng 60 giây cho mọi câu hỏi và nhận thêm +3 điểm thưởng khi trả lời nhanh dưới 12 giây!',
    limitType: 'continuous',
    maxUses: 999,
    unlockedLevel: 1,
  },
  {
    id: 'rune_swap_question',
    name: 'Rune Hoán Đổi',
    category: 'TIME',
    categoryNameVi: 'Thời Gian',
    icon: 'Shuffle',
    color: '#818cf8',
    description: 'Đổi câu hỏi Toán khó sang câu mới (1 lần/lượt).',
    persistentEffectDesc: 'HOÁN ĐỔI (1 LẦN/LƯỢT): Cho phép bấm đổi câu hỏi toán khó sang một câu mới dễ hơn (tối đa 1 lần/lượt)!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },

  // 🟡 NHÓM ĐIỂM SỐ (POINTS)
  {
    id: 'rune_double',
    name: 'Rune Nhân Đôi',
    category: 'POINTS',
    categoryNameVi: 'Điểm Số',
    icon: 'Sparkles',
    color: '#eab308',
    description: 'Gia tăng điểm số lá bài (1 lần/lượt).',
    persistentEffectDesc: 'NHÂN ĐIỂM (1 LẦN/LƯỢT): Nhân x1.5 điểm cho 1 lá bài giải đúng trong mỗi lượt thi đấu!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },
  {
    id: 'rune_bank_bonus',
    name: 'Rune Tích Lũy',
    category: 'POINTS',
    categoryNameVi: 'Điểm Số',
    icon: 'Coins',
    color: '#facc15',
    description: 'Cộng điểm thưởng khi cất giữ (1 lần/lượt).',
    persistentEffectDesc: 'KHO BÁU (1 LẦN/LƯỢT): Mỗi lần bạn bấm BANK, tự động nhận thêm +15 điểm thưởng trực tiếp vào kho an toàn!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },
  {
    id: 'rune_harvest',
    name: 'Rune Thu Hoạch',
    category: 'POINTS',
    categoryNameVi: 'Điểm Số',
    icon: 'Award',
    color: '#fbbf24',
    description: 'Thưởng chuỗi bài lớn (1 lần/lượt).',
    persistentEffectDesc: 'BỘI THU (1 LẦN/LƯỢT): Mỗi khi gom được từ 3 lá bài trở lên trên bàn trong lượt, nhận thêm +15 điểm thưởng (tối đa 1 lần/lượt)!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },
  {
    id: 'rune_siphon',
    name: 'Rune Đạo Tặc',
    category: 'POINTS',
    categoryNameVi: 'Điểm Số',
    icon: 'Flame',
    color: '#d97706',
    description: 'Hút điểm từ kho của đối thủ (1 lần/lượt).',
    persistentEffectDesc: 'MA HÚT (1 LẦN/LƯỢT): Hút 3 điểm an toàn từ đối thủ sang kho của bạn ở câu trả lời đúng đầu tiên trong mỗi lượt!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },

  // 🟣 NHÓM MA THUẬT (MAGIC)
  {
    id: 'rune_foresight',
    name: 'Rune Tiên Tri',
    category: 'MAGIC',
    categoryNameVi: 'Ma Thuật',
    icon: 'Eye',
    color: '#a855f7',
    description: 'Xem trước lá bài trên đỉnh bộ bài.',
    persistentEffectDesc: 'THẤU THỊ: Luôn nhìn thấy trước hệ và điểm số của lá bài tiếp theo trên đỉnh bộ bài để né BUST!',
    limitType: 'continuous',
    maxUses: 999,
    unlockedLevel: 1,
  },
  {
    id: 'rune_purify',
    name: 'Rune Thanh Lọc',
    category: 'MAGIC',
    categoryNameVi: 'Ma Thuật',
    icon: 'Feather',
    color: '#c084fc',
    description: 'Thanh lọc lá bài nguy hiểm trên bàn (1 lần/lượt).',
    persistentEffectDesc: 'THANH LỌC (1 LẦN/LƯỢT): Xóa bỏ 1 lá bài đã có trên bàn để giảm nguy cơ Bust trùng hệ (tối đa 1 lần/lượt)!',
    limitType: 'once_per_turn',
    maxUses: 1,
    unlockedLevel: 1,
  },
  {
    id: 'rune_frenzy',
    name: 'Rune Cuồng Nộ',
    category: 'MAGIC',
    categoryNameVi: 'Ma Thuật',
    icon: 'Swords',
    color: '#ec4899',
    description: 'Cường hóa toàn bộ điểm số.',
    persistentEffectDesc: 'CHIẾN Ý: Toàn bộ điểm số kiếm được khi giải đúng câu hỏi được tăng +25% điểm!',
    limitType: 'continuous',
    maxUses: 999,
    unlockedLevel: 1,
  },
  {
    id: 'rune_immortal',
    name: 'Rune Bất Tử',
    category: 'MAGIC',
    categoryNameVi: 'Ma Thuật',
    icon: 'Crown',
    color: '#f43f5e',
    description: 'Chặn thua cuộc và trao cơ hội lật kèo (Duy nhất 1 lần/trận).',
    persistentEffectDesc: 'BẤT TỬ CẢNH GIỚI (DUY NHẤT 1 LẦN/TRẬN): Khi đối thủ chạm mốc 150 điểm, tự động chặn đứng chiến thắng, giảm 30 điểm của họ và mở ra vòng đấu lội ngược dòng. Chỉ kích hoạt ĐÚNG 1 LẦN duy nhất trong cả trận!',
    limitType: 'once_per_match',
    maxUses: 1,
    unlockedLevel: 1,
  },
];

export const DEFAULT_RUNE_SELECTION = ['rune_shield'];
